/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The directory where Fontjam stores font libraries.
 */
export type FontLibraryDirectory = string;
/**
 * Directory where databases files are saved.
 */
export type DatabaseDirectory = string;

export interface ConfigSchema {
  "library.url": FontLibraryDirectory;
  "db.url": DatabaseDirectory;
}
